import 'package:flutter_test/flutter_test.dart';

import 'package:european_dream/core/domain/enums.dart';
import 'package:european_dream/core/domain/models.dart';
import 'package:european_dream/core/domain/settings.dart';
import 'package:european_dream/core/services/metrics_service.dart';
import 'package:european_dream/core/services/plan_generator.dart';
import 'package:european_dream/core/services/scoring_service.dart';
import 'package:european_dream/core/services/streak_service.dart';

AppSettings settingsFor({
  int weeklyApplications = 40,
  PlanMode mode = PlanMode.flexible,
  double streakThreshold = 0.6,
}) => AppSettings(
  targetDeadline: DateTime(2027, 2, 28),
  weeklyApplications: weeklyApplications,
  weeklyRecruiterMessages: 20,
  weeklyConnections: 25,
  weeklyFollowUps: 12,
  weeklyPrepMinutes: 300,
  weeklyCompanyResearch: 10,
  weeklyHiringManagerMessages: 4,
  weeklyAgencyRegistrations: 5,
  planMode: mode,
  streakThreshold: streakThreshold,
  countryTargets: AppSettings.defaultCountryTargets,
  roleTargets: AppSettings.defaultRoleTargets,
);

JobApplication app({
  required String country,
  ApplicationStage stage = ApplicationStage.applied,
  String role = 'Backend Engineer',
  DateTime? applied,
  WorkAuthRequirement auth = WorkAuthRequirement.unknown,
  int skill = 7,
  int experience = 6,
  String? resumeId,
  DateTime? response,
  DateTime? interview,
}) {
  final now = DateTime.now();
  return JobApplication(
    id:
        'a${country}_${stage.id}_${applied?.millisecondsSinceEpoch ?? 0}'
        '_${role.hashCode}_${resumeId ?? ''}',
    jobTitle: 'Engineer',
    companyName: 'Acme',
    country: country,
    roleCategory: role,
    stage: stage,
    workAuthRequirement: auth,
    skillMatch: skill,
    experienceMatch: experience,
    resumeId: resumeId,
    dateDiscovered: applied ?? now,
    // a closed stage still records the date it was actually sent
    dateApplied: (stage.hasApplied || stage.isClosed) ? (applied ?? now) : null,
    responseDate: response,
    interviewDate: interview,
    createdAt: applied ?? now,
    updatedAt: now,
  );
}

DailyTask task({
  required DateTime date,
  required String recurrence,
  TaskCategory category = TaskCategory.applications,
  int target = 6,
  int completed = 0,
  TaskStatus status = TaskStatus.notStarted,
  int actualMinutes = 0,
}) {
  final now = DateTime.now();
  return DailyTask(
    id: '$recurrence-${date.toIso8601String()}-$completed',
    title: recurrence,
    date: dayOf(date),
    category: category,
    status: status,
    targetCount: target,
    completedCount: completed,
    actualMinutes: actualMinutes,
    recurrence: recurrence,
    isAutoGenerated: true,
    createdAt: now,
    updatedAt: now,
  );
}

void main() {
  group('PlanGenerator', () {
    test('spreads the weekly quota across the days that remain', () {
      // Monday: 7 days left, 40 applications would be 6, but the daily
      // workflow caps application work at a humane 4.
      final monday = DateTime(2026, 8, 31); // a Monday
      expect(monday.weekday, DateTime.monday);

      final tasks = PlanGenerator(
        settingsFor(),
      ).generate(date: monday, weekTasks: const [], weekLogs: const []);

      final applications = tasks.firstWhere(
        (t) => t.recurrence == 'applications',
      );
      expect(applications.targetCount, 4);
      expect(applications.category, TaskCategory.applications);
      expect(applications.priority, TaskPriority.critical);
    });

    test('redistributes rather than repeating after a missed day', () {
      // Wednesday with nothing done Mon/Tue: 5 days left, all 40 remain
      final monday = DateTime(2026, 8, 31);
      final wednesday = monday.add(const Duration(days: 2));

      final missed = [
        task(date: monday, recurrence: 'applications', completed: 0),
        task(
          date: monday.add(const Duration(days: 1)),
          recurrence: 'applications',
          completed: 0,
        ),
      ];

      final tasks = PlanGenerator(
        settingsFor(),
      ).generate(date: wednesday, weekTasks: missed, weekLogs: const []);

      final applications = tasks.firstWhere(
        (t) => t.recurrence == 'applications',
      );
      // 40 remaining over 5 days = 8, but daily application work is capped.
      expect(applications.targetCount, 4);
    });

    test('subtracts work already completed earlier in the week', () {
      final monday = DateTime(2026, 8, 31);
      final wednesday = monday.add(const Duration(days: 2));

      final done = [
        task(date: monday, recurrence: 'applications', completed: 10),
        task(
          date: monday.add(const Duration(days: 1)),
          recurrence: 'applications',
          completed: 10,
        ),
      ];

      final tasks = PlanGenerator(
        settingsFor(),
      ).generate(date: wednesday, weekTasks: done, weekLogs: const []);

      final applications = tasks.firstWhere(
        (t) => t.recurrence == 'applications',
      );
      // 20 remaining over 5 days = 4
      expect(applications.targetCount, 4);
    });

    test('strict mode keeps a fixed daily quota', () {
      final monday = DateTime(2026, 8, 31);
      final friday = monday.add(const Duration(days: 4));

      final tasks = PlanGenerator(
        settingsFor(mode: PlanMode.strict),
      ).generate(date: friday, weekTasks: const [], weekLogs: const []);

      final applications = tasks.firstWhere(
        (t) => t.recurrence == 'applications',
      );
      expect(applications.targetCount, 4); // capped even in strict mode
    });

    test('catch-up mode front-loads the backlog', () {
      final monday = DateTime(2026, 8, 31);
      final wednesday = monday.add(const Duration(days: 2));

      final flexible = PlanGenerator(
        settingsFor(),
      ).generate(date: wednesday, weekTasks: const [], weekLogs: const []);
      final catchUp = PlanGenerator(
        settingsFor(mode: PlanMode.catchUp),
      ).generate(date: wednesday, weekTasks: const [], weekLogs: const []);

      final f = flexible.firstWhere((t) => t.recurrence == 'applications');
      final c = catchUp.firstWhere((t) => t.recurrence == 'applications');
      expect(c.targetCount, f.targetCount);
      expect(c.targetCount, 4);
    });

    test('prep minutes are rounded to a 15-minute block', () {
      final monday = DateTime(2026, 8, 31);
      final tasks = PlanGenerator(
        settingsFor(),
      ).generate(date: monday, weekTasks: const [], weekLogs: const []);
      final prep = tasks.firstWhere((t) => t.recurrence == 'preparation');
      expect(prep.estimatedMinutes % 15, 0);
    });

    test('a quota already met for the week produces no task', () {
      final monday = DateTime(2026, 8, 31);
      final friday = monday.add(const Duration(days: 4));

      final done = [
        for (var i = 0; i < 4; i++)
          task(
            date: monday.add(Duration(days: i)),
            recurrence: 'applications',
            completed: 10,
          ),
      ];

      final tasks = PlanGenerator(
        settingsFor(),
      ).generate(date: friday, weekTasks: done, weekLogs: const []);
      expect(tasks.where((t) => t.recurrence == 'applications'), isEmpty);
    });

    test('uses due follow-ups as named daily tasks before generic quota', () {
      final monday = DateTime(2026, 8, 31);
      final now = DateTime.now();
      final tasks = PlanGenerator(settingsFor()).generate(
        date: monday,
        weekTasks: const [],
        weekLogs: const [],
        context: PlanContext(
          followUps: [
            FollowUp(
              id: 'f1',
              title: 'Follow up: Backend Engineer',
              dueDate: monday.subtract(const Duration(days: 1)),
              context: 'Acme · Germany',
              recommendedAction: 'Send a concise status check.',
              createdAt: now,
              updatedAt: now,
            ),
          ],
        ),
      );

      final followUp = tasks.firstWhere((t) => t.recurrence == 'follow_up:f1');
      expect(followUp.title, 'Overdue follow-up: Backend Engineer');
      expect(followUp.category, TaskCategory.followUps);
      expect(followUp.priority, TaskPriority.critical);

      final followUpCount = tasks
          .where((t) => t.category == TaskCategory.followUps)
          .fold(0, (sum, t) => sum + t.targetCount);
      expect(followUpCount, lessThanOrEqualTo(4));
    });

    test('suggests specific saved opportunities for application work', () {
      final monday = DateTime(2026, 8, 31);
      final now = DateTime.now();
      final tasks = PlanGenerator(settingsFor(weeklyApplications: 2)).generate(
        date: monday,
        weekTasks: const [],
        weekLogs: const [],
        context: PlanContext(
          opportunities: [
            JobOpportunity(
              id: 'o1',
              jobTitle: 'Flutter Engineer',
              companyName: 'Care Assistant',
              country: 'Germany',
              status: OpportunityStatus.readyToApply,
              priority: TaskPriority.high,
              dateDiscovered: monday,
              createdAt: now,
              updatedAt: now,
            ),
          ],
        ),
      );

      final application = tasks.firstWhere(
        (t) => t.recurrence == 'opportunity:o1',
      );
      expect(application.title, 'Apply: Flutter Engineer at Care Assistant');
      expect(application.country, 'Germany');
      expect(application.notes, contains('saved opportunity'));
    });
  });

  group('ScoringService', () {
    final scoring = ScoringService(settingsFor());

    test('explicit sponsorship in a primary market scores highly', () {
      final score = scoring.score(
        app(
          country: 'Germany',
          auth: WorkAuthRequirement.explicitSponsorship,
          skill: 9,
          experience: 9,
        ),
      );
      expect(score, greaterThan(75));
    });

    test('EU-only in an untargeted country scores poorly', () {
      final score = scoring.score(
        app(
          country: 'Iceland',
          auth: WorkAuthRequirement.euOnly,
          skill: 4,
          experience: 3,
          role: 'QA Engineer',
        ),
      );
      expect(score, lessThan(40));
    });

    test('Germany outranks an equivalent role elsewhere', () {
      final germany = scoring.score(app(country: 'Germany'));
      final italy = scoring.score(app(country: 'Italy'));
      expect(germany, greaterThan(italy));
    });

    test('score stays within 0-100 at both extremes', () {
      final best = scoring.score(
        app(
          country: 'Germany',
          auth: WorkAuthRequirement.explicitSponsorship,
          skill: 10,
          experience: 10,
        ),
      );
      final worst = scoring.score(
        app(
          country: 'Iceland',
          auth: WorkAuthRequirement.euOnly,
          skill: 0,
          experience: 0,
          role: 'Other',
        ),
      );
      expect(best, inInclusiveRange(0, 100));
      expect(worst, inInclusiveRange(0, 100));
    });

    test('breakdown contributions sum to the total score', () {
      final a = app(country: 'Netherlands');
      final total = scoring.score(a);
      final sum = scoring
          .breakdown(a)
          .fold<double>(0, (s, c) => s + c.contribution);
      expect(sum, closeTo(total, 0.001));
    });
  });

  group('ApplicationMetrics', () {
    test('rates are computed over submitted applications only', () {
      final metrics = ApplicationMetrics([
        app(country: 'Germany', stage: ApplicationStage.saved),
        app(country: 'Germany', stage: ApplicationStage.applied),
        app(country: 'Germany', stage: ApplicationStage.recruiterScreen),
        app(country: 'Netherlands', stage: ApplicationStage.technicalInterview),
        app(country: 'Netherlands', stage: ApplicationStage.offer),
      ], settingsFor());

      // saved is not submitted
      expect(metrics.total, 4);
      expect(metrics.totalSaved, 5);
      expect(metrics.responses, 3); // recruiterScreen, technical, offer
      expect(metrics.interviews, 2); // technical, offer
      expect(metrics.offers, 1);
      expect(metrics.responseRate, closeTo(0.75, 0.001));
      expect(metrics.offerRate, closeTo(0.25, 0.001));
    });

    test('a rejected application keeps the milestones its dates prove', () {
      final now = DateTime.now();
      final metrics = ApplicationMetrics([
        app(
          country: 'Germany',
          stage: ApplicationStage.rejected,
          applied: now.subtract(const Duration(days: 20)),
          response: now.subtract(const Duration(days: 10)),
          interview: now.subtract(const Duration(days: 5)),
        ),
      ], settingsFor());

      expect(metrics.total, 1);
      expect(metrics.responses, 1);
      expect(metrics.interviews, 1);

      final funnel = {for (final f in metrics.funnel) f.label: f.count};
      expect(funnel['Applied'], 1);
      expect(funnel['Response'], 1);
      expect(funnel['Interview'], 1);
      expect(funnel['Offer'], 0);
    });

    test('country allocation compares target against actual', () {
      final metrics = ApplicationMetrics([
        for (var i = 0; i < 9; i++) app(country: 'Germany'),
        app(country: 'Netherlands'),
      ], settingsFor());

      final alloc = metrics.countryAllocation();
      final germany = alloc.firstWhere((a) => a.country == 'Germany');
      final netherlands = alloc.firstWhere((a) => a.country == 'Netherlands');

      expect(germany.actualPercent, closeTo(90, 0.01));
      expect(germany.isOver, isTrue); // target 45%
      expect(netherlands.actualPercent, closeTo(10, 0.01));
      expect(netherlands.isUnder, isTrue); // target 30%

      // gap tells you how many more NL applications restore the balance
      final gap = ApplicationMetrics.gapToTarget(netherlands, metrics.total);
      expect(gap, 2); // 30% of 10 = 3, minus the 1 already sent
    });

    test('aging health tracks days since applying', () {
      final now = DateTime.now();
      final fresh = app(
        country: 'Germany',
        applied: now.subtract(const Duration(days: 2)),
      );
      final waiting = app(
        country: 'Germany',
        applied: now.subtract(const Duration(days: 9)),
      );
      final due = app(
        country: 'Germany',
        applied: now.subtract(const Duration(days: 16)),
      );
      final stale = app(
        country: 'Germany',
        applied: now.subtract(const Duration(days: 30)),
      );

      expect(fresh.health(), ApplicationHealth.active);
      expect(waiting.health(), ApplicationHealth.waiting);
      expect(due.health(), ApplicationHealth.followUpDue);
      expect(stale.health(), ApplicationHealth.stale);

      // a closed application is never chased
      expect(
        app(country: 'Germany', stage: ApplicationStage.rejected).health(),
        ApplicationHealth.closed,
      );
    });
  });

  group('StreakService', () {
    final service = StreakService(settingsFor());

    test('a day clearing the threshold extends the streak', () {
      final today = dayOf(DateTime.now());
      final tasks = [
        for (var i = 0; i < 3; i++)
          task(
            date: today.subtract(Duration(days: i)),
            recurrence: 'applications',
            target: 4,
            completed: 4,
            status: TaskStatus.completed,
          ),
      ];

      final stats = service.compute(allTasks: tasks, logs: const []);
      expect(stats.current, 3);
      expect(stats.best, greaterThanOrEqualTo(3));
    });

    test('an unfinished day breaks the streak', () {
      final today = dayOf(DateTime.now());
      final tasks = [
        // yesterday: nothing done
        task(
          date: today.subtract(const Duration(days: 1)),
          recurrence: 'applications',
          target: 4,
          completed: 0,
        ),
        // two days ago: complete
        task(
          date: today.subtract(const Duration(days: 2)),
          recurrence: 'applications',
          target: 4,
          completed: 4,
          status: TaskStatus.completed,
        ),
      ];

      final stats = service.compute(allTasks: tasks, logs: const []);
      expect(stats.current, 0);
      expect(stats.best, 1);
    });

    test('an explicit rest day preserves the streak', () {
      final today = dayOf(DateTime.now());
      final yesterday = today.subtract(const Duration(days: 1));
      final twoDaysAgo = today.subtract(const Duration(days: 2));

      final tasks = [
        task(
          date: today,
          recurrence: 'applications',
          target: 4,
          completed: 4,
          status: TaskStatus.completed,
        ),
        task(
          date: yesterday,
          recurrence: 'applications',
          target: 4,
          completed: 0,
        ),
        task(
          date: twoDaysAgo,
          recurrence: 'applications',
          target: 4,
          completed: 4,
          status: TaskStatus.completed,
        ),
      ];

      final withoutRest = service.compute(allTasks: tasks, logs: const []);
      expect(withoutRest.current, 1);

      final withRest = service.compute(
        allTasks: tasks,
        logs: [DayLog(date: yesterday, dayType: DayType.rest)],
      );
      expect(withRest.current, 3);
    });

    test('today not yet done does not break an existing streak', () {
      final today = dayOf(DateTime.now());
      final tasks = [
        // today: started but incomplete
        task(date: today, recurrence: 'applications', target: 4, completed: 1),
        for (var i = 1; i <= 3; i++)
          task(
            date: today.subtract(Duration(days: i)),
            recurrence: 'applications',
            target: 4,
            completed: 4,
            status: TaskStatus.completed,
          ),
      ];

      final stats = service.compute(allTasks: tasks, logs: const []);
      expect(stats.current, 3);
    });

    test('partial progress produces a proportional score', () {
      final today = dayOf(DateTime.now());
      final score = service.scoreFor(
        date: today,
        tasks: [
          task(
            date: today,
            recurrence: 'applications',
            target: 4,
            completed: 2,
          ),
        ],
      );
      expect(score.score, closeTo(50, 0.01));
      // 50 falls in the 50..79 band
      expect(score.intensity, 3);
    });
  });
}
